# Generated by Django 6.0 on 2026-01-15 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "Usuario"), ("assistant", "Asistente")],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Mensaje de Chat",
                "verbose_name_plural": "Mensajes de Chat",
                "ordering": ["timestamp"],
            },
        ),
    ]
