# Generated by Django 6.0.1 on 2026-01-15 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('query_type', models.CharField(max_length=100)),
                ('query_description', models.TextField()),
                ('query_params', models.JSONField()),
                ('result_data', models.JSONField()),
                ('result_summary', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Consulta Cacheada',
                'verbose_name_plural': 'Consultas Cacheadas',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session_id', '-timestamp'], name='main_queryc_session_7ecf73_idx')],
            },
        ),
    ]
